### ISSUE TITLE
Multiple test failures using AdoptOpenJDK 8u252

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-grpc#253]
See https://github.com/akka/akka-grpc/issues/946

TL,DR; supporting ALPN in the JDK directly (added in 8u252) requires upstream libraries to adapt how ALPN is used.

**Comment by raboof** [comment]
What is the way forward here? I see a couple of options:
* Support JDK11 and JDK8, but JDK8 only before 8u252 (until https://github.com/grpc/grpc-java/pull/7060 makes it)
* Support JDK11, drop support for JDK8
* Support JDK11, JDK8 < 8u252 and JDK8u252-with-native-openssl (which means refactoring things so we can provide TrustManager implementations rather than an SSLContext).

I'm leaning towards '2' or '1'.

**Comment by ignasi35** [comment]
> I'm leaning towards '2' or '1'.

Agreed.

**Comment by raboof** [comment]
grpc/grpc-java#7060 has since made it into 1.32.1 and akka-grpc 1.0.2 has updated to that version

**Comment by raboof** [comment]
(Not tested in depth but trusting CI here :crossed_fingers: )
